<a href="https://colab.research.google.com/github/Anirudh1905/Data_Analytics/blob/master/Reg_3(train_test).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
from scipy import stats
import numpy as np
import statsmodels.api as sm
from sklearn import linear_model
from sklearn.metrics import mean_squared_error

In [4]:
data=pd.read_excel('/content/drive/My Drive/Colab Notebooks/HARDNESS.xls')
data

Tensile strength  Hardness
0               53.0     29.31
1               70.2     34.86
2               84.3     36.82
3               55.3     30.12
4               78.5     34.02
5               63.5     30.82
6               71.4     35.40
7               53.4     31.26
8               82.5     32.18
9               67.3     33.42
10              69.5     37.69
11              73.0     34.88
12              55.7     24.66
13              85.8     34.76
14              95.4     38.02
15              51.1     25.68
16              74.4     25.81
17              54.1     26.46
18              77.8     28.67
19              52.4     24.64
20              69.1     25.77
21              53.5     23.69
22              64.3     28.65
23              82.7     32.38
24              55.7     23.21
25              70.5     34.00
26              87.5     34.47
27              50.7     29.25
28              72.3     28.71
29              59.5     29.83
30              71.3     29.25
31              52.7     27.99
32              76.5     31.85
33              63.7     27.65
34              69.2     31.70

In [16]:
from sklearn.model_selection import train_test_split
x=data['Hardness'].values.reshape(-1,1)
y=data['Tensile strength'].values.reshape(-1,1)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=88)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((28, 1), (7, 1), (28, 1), (7, 1))

In [17]:
x_train

array([[38.02],
       [34.76],
       [32.18],
       [29.31],
       [23.69],
       [30.12],
       [27.65],
       [29.25],
       [35.4 ],
       [27.99],
       [28.67],
       [31.26],
       [34.02],
       [34.88],
       [29.25],
       [36.82],
       [34.47],
       [24.66],
       [28.71],
       [25.81],
       [34.86],
       [30.82],
       [25.77],
       [37.69],
       [26.46],
       [25.68],
       [31.85],
       [23.21]])

In [18]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [19]:
reg.intercept_

array([7.045691])

In [20]:
reg.coef_

array([[1.99777401]])

In [21]:
y_predict=reg.predict(x_test)
y_predict

array([[73.81129842],
       [56.27084261],
       [64.28191639],
       [66.63928973],
       [70.37512713],
       [74.97000735],
       [71.73361345]])

In [22]:
mean_squared_error(y_test,y_predict)

35.71053398209997

In [23]:
reg.score(x_test,y_test)

0.5362243730094254

In [24]:
reg.score(x_train,y_train)

0.4500146647765303